### ISSUE TITLE
[index][render] Use of raw HTML and Bootstrap property beats the purpose of the assignment

### ISSUE THREAD

**Issue by heyapricot** [osinakayah/js-library#2]
Having your `render` function return raw HTML and use the of Bootstrap data-attributes defeats the purpose of the assignment. 
Use `document.createElement` and `appendChild()` instead

**Comment by osinakayah** [comment]
Done. We have refactored the code to use document.createElement and appendChild().

**Comment by osinakayah** [comment]
Done. I am making use of createElement and appendChild() now. 
Regarding the bootstrap inclusion, one of the courses in our curriculum  included learning how to use bootstrap, so this was opportunity to apply the knowledge we have acquired in the bootstrap section of the course.

**Comment by heyapricot** [comment]
I have no problem with the project using bootstrap to handle things like CSS. Where I think it beats the purpose of the assignment is in the particular use of the `data-attributes`
